# Generated by Django 4.1 on 2023-06-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_mycontact_mycv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycontact',
            old_name='likendin',
            new_name='linkedin',
        ),
    ]
