# Generated by Django 4.1 on 2023-04-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_live_code',
            new_name='published',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='view_code',
            field=models.CharField(max_length=255),
        ),
    ]
