# Generated by Django 4.1 on 2024-03-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_created_at_project_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
