# Generated by Django 4.1 on 2023-04-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='value',
        ),
    ]
