# Generated by Django 4.1 on 2024-02-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_rename_title_skill_name_rename_skill_skill_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='value',
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/technologies/'),
        ),
    ]
