# Generated by Django 4.1 on 2024-02-19 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_skill_confident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/technologies/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
